import React from "react"
// App.js'te <Card />' ekleyeceğim attributesler'i tek bir variable object olarak topluyorum
const Personality = [
  {
    name: "Ömer Çetin(s)",
    imgId: "ömer-img",
    imgSrc: "images/ömer-img.jpeg",
    aboutId: "about-omer",
    battleId: "omer-battle",
    kahpelik: "Kahpelik: %50",
    zeka: "Zeka: %40",
    motosiklet: "Motosiklet: %70",
    sans: "Şans: %90",
    personalityOne: "Şans: %90",
    personalityTwo: "GÜÇ",
    personalityThree: "UZUN BOY",
    personalityFour: "kellik",
  },
  {
    name: "Çağrı Genç",
    imgId: "cagrı-img",
    imgSrc: "images/cagrı-img.jpeg",
    aboutId: "about-cagrı",
    battleId: "cagrı-battle",
    kahpelik: "Kahpelik: %70",
    zeka: "Zeka: %39",
    motosiklet: "Motosiklet: %0",
    sans: "Şans: %50",
    personalityOne: "YAKIŞIKLILIK",
    personalityTwo: "UZUN BURUN",
    personalityThree: "DUŞ ALMAMAK",
    personalityFour: "CAMEL İÇEBİLMEK",
  },
  {
    name: "Doğukan Güler",
    imgId: "dogi-img",
    imgSrc: "images/dogi-img.jpeg",
    aboutId: "about-dogi",
    battleId: "dogi-battle",
    kahpelik: "Kahpelik: %200",
    zeka: "Zeka: %39",
    motosiklet: "Motosiklet: %90",
    sans: "Şans: HAHAHA",
    personalityOne: "TEKEL BAYİCİ",
    personalityTwo: "BURUN TERLEMESİ",
    personalityThree: "CLASH OF ROYALE",
    personalityFour: "TELEFON AÇMAMA",
  },
  {
    name: "Yasir Ç.",
    imgId: "yasir-img",
    imgSrc: "images/yasir-img.jpeg",
    aboutId: "about-yasir",
    battleId: "yasir-battle",
    kahpelik: "Kahpelik: %0",
    zeka: "Zeka: %100",
    motosiklet: "Motosiklet: %100",
    sans: "Şans: %50",
    personalityOne: "YAKIŞIKLILIK",
    personalityTwo: "SÜPER ZEKA",
    personalityThree: "PRATİKLİK",
    personalityFour: "HÜKMETMEK",
  },
]

export default Personality
